[package]
name = 'iptooled'
version = '0.1.0'

edition = '2018'

repository = 'https://github.com/charmander/iptooled'

[dependencies]
getrandom = '0.1.13'
siphasher = '0.3.1'

[dependencies.tokio]
version = '0.2.4'
features = [
	'fs',
	'io-util',
	'rt-core',
	'rt-util',
	'sync',
	'uds',
]
