[package]
name = 'iptooled'
version = '0.1.0'

edition = '2018'

repository = 'https://github.com/charmander/iptooled'

[dependencies.tokio]
version = '0.2.2'
features = [
	'io-util',
	'rt-core',
	'rt-util',
	'uds',
]
